# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         VCS-SnapshotCM
version:      0.02
version_from: lib/VCS/SnapshotCM/Tools.pm
installdirs:  site
requires:
    Data::Dumper:                  0
    File::Temp:                    0
    Getopt::Long:                  0
    Pod::Usage:                    0
    POSIX:                         0
    Term::ANSIColor:               0
    Text::Tabs:                    0
    Text::Wrap:                    0
    Time::Local:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
